// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: im_ws.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IMWebsocket_ServerPushMsgToUser_FullMethodName = "/im_ws.IMWebsocket/ServerPushMsgToUser"
)

// IMWebsocketClient is the client API for IMWebsocket service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 定义服务
type IMWebsocketClient interface {
	ServerPushMsgToUser(ctx context.Context, in *ServerPushMsgToUserRequest, opts ...grpc.CallOption) (*ServerPushMsgToUserResponse, error)
}

type iMWebsocketClient struct {
	cc grpc.ClientConnInterface
}

func NewIMWebsocketClient(cc grpc.ClientConnInterface) IMWebsocketClient {
	return &iMWebsocketClient{cc}
}

func (c *iMWebsocketClient) ServerPushMsgToUser(ctx context.Context, in *ServerPushMsgToUserRequest, opts ...grpc.CallOption) (*ServerPushMsgToUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerPushMsgToUserResponse)
	err := c.cc.Invoke(ctx, IMWebsocket_ServerPushMsgToUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IMWebsocketServer is the server API for IMWebsocket service.
// All implementations must embed UnimplementedIMWebsocketServer
// for forward compatibility.
//
// 定义服务
type IMWebsocketServer interface {
	ServerPushMsgToUser(context.Context, *ServerPushMsgToUserRequest) (*ServerPushMsgToUserResponse, error)
	mustEmbedUnimplementedIMWebsocketServer()
}

// UnimplementedIMWebsocketServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIMWebsocketServer struct{}

func (UnimplementedIMWebsocketServer) ServerPushMsgToUser(context.Context, *ServerPushMsgToUserRequest) (*ServerPushMsgToUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServerPushMsgToUser not implemented")
}
func (UnimplementedIMWebsocketServer) mustEmbedUnimplementedIMWebsocketServer() {}
func (UnimplementedIMWebsocketServer) testEmbeddedByValue()                     {}

// UnsafeIMWebsocketServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IMWebsocketServer will
// result in compilation errors.
type UnsafeIMWebsocketServer interface {
	mustEmbedUnimplementedIMWebsocketServer()
}

func RegisterIMWebsocketServer(s grpc.ServiceRegistrar, srv IMWebsocketServer) {
	// If the following call pancis, it indicates UnimplementedIMWebsocketServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IMWebsocket_ServiceDesc, srv)
}

func _IMWebsocket_ServerPushMsgToUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerPushMsgToUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IMWebsocketServer).ServerPushMsgToUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IMWebsocket_ServerPushMsgToUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IMWebsocketServer).ServerPushMsgToUser(ctx, req.(*ServerPushMsgToUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IMWebsocket_ServiceDesc is the grpc.ServiceDesc for IMWebsocket service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IMWebsocket_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "im_ws.IMWebsocket",
	HandlerType: (*IMWebsocketServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ServerPushMsgToUser",
			Handler:    _IMWebsocket_ServerPushMsgToUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "im_ws.proto",
}
