// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: im_ws.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageContent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MsgType        int32                  `protobuf:"varint,2,opt,name=msgType,proto3" json:"msgType,omitempty"`
	ConversationID string                 `protobuf:"bytes,3,opt,name=conversationID,proto3" json:"conversationID,omitempty"`
	Sender         string                 `protobuf:"bytes,4,opt,name=sender,proto3" json:"sender,omitempty"`
	Message        string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageContent) Reset() {
	*x = MessageContent{}
	mi := &file_im_ws_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageContent) ProtoMessage() {}

func (x *MessageContent) ProtoReflect() protoreflect.Message {
	mi := &file_im_ws_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageContent.ProtoReflect.Descriptor instead.
func (*MessageContent) Descriptor() ([]byte, []int) {
	return file_im_ws_proto_rawDescGZIP(), []int{0}
}

func (x *MessageContent) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *MessageContent) GetConversationID() string {
	if x != nil {
		return x.ConversationID
	}
	return ""
}

func (x *MessageContent) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *MessageContent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 定义请求消息
type ServerPushMsgToUserRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserID         string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	MessageContent *MessageContent        `protobuf:"bytes,2,opt,name=messageContent,proto3" json:"messageContent,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ServerPushMsgToUserRequest) Reset() {
	*x = ServerPushMsgToUserRequest{}
	mi := &file_im_ws_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerPushMsgToUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPushMsgToUserRequest) ProtoMessage() {}

func (x *ServerPushMsgToUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_im_ws_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerPushMsgToUserRequest.ProtoReflect.Descriptor instead.
func (*ServerPushMsgToUserRequest) Descriptor() ([]byte, []int) {
	return file_im_ws_proto_rawDescGZIP(), []int{1}
}

func (x *ServerPushMsgToUserRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *ServerPushMsgToUserRequest) GetMessageContent() *MessageContent {
	if x != nil {
		return x.MessageContent
	}
	return nil
}

// 定义响应消息
type ServerPushMsgToUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerPushMsgToUserResponse) Reset() {
	*x = ServerPushMsgToUserResponse{}
	mi := &file_im_ws_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerPushMsgToUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPushMsgToUserResponse) ProtoMessage() {}

func (x *ServerPushMsgToUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_im_ws_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerPushMsgToUserResponse.ProtoReflect.Descriptor instead.
func (*ServerPushMsgToUserResponse) Descriptor() ([]byte, []int) {
	return file_im_ws_proto_rawDescGZIP(), []int{2}
}

func (x *ServerPushMsgToUserResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ServerPushMsgToUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_im_ws_proto protoreflect.FileDescriptor

var file_im_ws_proto_rawDesc = string([]byte{
	0x0a, 0x0b, 0x69, 0x6d, 0x5f, 0x77, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x69,
	0x6d, 0x5f, 0x77, 0x73, 0x22, 0x84, 0x01, 0x0a, 0x0e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x73, 0x67, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x26, 0x0a, 0x0e, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x76, 0x65,
	0x72, 0x73, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x73, 0x0a, 0x1a, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x73, 0x67, 0x54, 0x6f, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x12, 0x3d, 0x0a, 0x0e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x69, 0x6d, 0x5f, 0x77,
	0x73, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x52, 0x0e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x22, 0x58, 0x0a, 0x1b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x73,
	0x67, 0x54, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x6b, 0x0a, 0x0b, 0x49, 0x4d,
	0x57, 0x65, 0x62, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x5c, 0x0a, 0x13, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x73, 0x67, 0x54, 0x6f, 0x55, 0x73, 0x65, 0x72,
	0x12, 0x21, 0x2e, 0x69, 0x6d, 0x5f, 0x77, 0x73, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x50,
	0x75, 0x73, 0x68, 0x4d, 0x73, 0x67, 0x54, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x69, 0x6d, 0x5f, 0x77, 0x73, 0x2e, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x73, 0x67, 0x54, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_im_ws_proto_rawDescOnce sync.Once
	file_im_ws_proto_rawDescData []byte
)

func file_im_ws_proto_rawDescGZIP() []byte {
	file_im_ws_proto_rawDescOnce.Do(func() {
		file_im_ws_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_im_ws_proto_rawDesc), len(file_im_ws_proto_rawDesc)))
	})
	return file_im_ws_proto_rawDescData
}

var file_im_ws_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_im_ws_proto_goTypes = []any{
	(*MessageContent)(nil),              // 0: im_ws.MessageContent
	(*ServerPushMsgToUserRequest)(nil),  // 1: im_ws.ServerPushMsgToUserRequest
	(*ServerPushMsgToUserResponse)(nil), // 2: im_ws.ServerPushMsgToUserResponse
}
var file_im_ws_proto_depIdxs = []int32{
	0, // 0: im_ws.ServerPushMsgToUserRequest.messageContent:type_name -> im_ws.MessageContent
	1, // 1: im_ws.IMWebsocket.ServerPushMsgToUser:input_type -> im_ws.ServerPushMsgToUserRequest
	2, // 2: im_ws.IMWebsocket.ServerPushMsgToUser:output_type -> im_ws.ServerPushMsgToUserResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_im_ws_proto_init() }
func file_im_ws_proto_init() {
	if File_im_ws_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_im_ws_proto_rawDesc), len(file_im_ws_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_im_ws_proto_goTypes,
		DependencyIndexes: file_im_ws_proto_depIdxs,
		MessageInfos:      file_im_ws_proto_msgTypes,
	}.Build()
	File_im_ws_proto = out.File
	file_im_ws_proto_goTypes = nil
	file_im_ws_proto_depIdxs = nil
}
